import React from "react";
import "./Marquee.css";

const Marquee = (props) => {
	return (
		<p
			className={`marquee ${props.extraClass} ${props.theme} ${props.color}`}>
			<span>
				WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE PROGRAMMER,
				FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER, ANDROID
				DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER, REACT
				DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER, WEB DEVELOPER, ANDROID DEVELOPER, COMPETITIVE
				PROGRAMMER, FRONTEND DEVELOPER, REACT DEVELOPER, WEB DEVELOPER,
				ANDROID DEVELOPER, COMPETITIVE PROGRAMMER, FRONTEND DEVELOPER,
				REACT DEVELOPER,{" "}
			</span>
		</p>
	);
};

export default Marquee;
